(defun f () 
	(setf test-hash (make-hash-table))
	(setf (gethash 'NB001 test-hash) "Mike")
	(setf (gethash 'NB002 test-hash) "Tom")
	(setf (gethash 'NB003 test-hash) "Edison")
	(format *query-io* "key: NB001 value: ~a~%" (gethash 'NB001 test-hash))
	(setf (gethash 'NB001 test-hash) "Alice")
	(format *query-io* "key: NB001 value: ~a~%" (gethash 'NB001 test-hash))
	(format *query-io* "print all hash elements:~%")
	(maphash #'(lambda (key value)
		(format *query-io* "key: ~a value: ~a~%" key value))
		test-hash)
)
