(defun f () 
	(setf test-hash (make-hash-table :test 'equal))
	(setf key1 "name")
	(setf key2 "age")
	(setf key3 "number")
	(setf (gethash key1 test-hash) "Mike")
	(setf (gethash key2 test-hash) "man")
	(setf (gethash key3 test-hash) "1234")
	(format *query-io* "key: ~a value: ~a~%" key1 (gethash key1 test-hash))
	(format *query-io* "key: ~a value: ~a~%" key2 (gethash key2 test-hash))
	(format *query-io* "print all hash elements:~%")
	(maphash #'(lambda (key value)
		(format *query-io* "key: ~a value: ~a~%" key value))
		test-hash)
)
