(defun f1 ()
	(setq v-1 1)
	(format *query-io* "v-1 = ~a in f1~%" v-1)
	(f2)
	(format *query-io* "v-1 = ~a after f2~%" v-1)
	(format *query-io* "v-2 = ~a in f2~%" v-2)
)
(defun f2 ()
	(setf v-2 2)
	(format *query-io* "v-1 =~a in f2~%" v-1) 
	(format *query-io* "v-2 =~a in f2~%" v-2) 
)
